name: Publish to JSR
on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish

    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Publish package
        run: npx jsr publish
